name: Type check Python 

description: Run Mypy and Pyright etc.

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:

  mypy:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          3.13,
        ]
        os: [
          "ubuntu-latest",
        ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install mypy
      run: pip install mypy

    - name: Install code for deps
      run: pip install -e .

  pyright:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          3.13,
        ]
        os: [
          "ubuntu-latest",
        ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: jakebailey/pyright-action@v2

